language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - mysql -uroot < tests/test.sql
  - psql -Upostgres -f tests/test.sql
  - touch tests/dummy/db/test.sqlite3
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
